#!/usr/bin/env python3
import sys
import argparse

"""
Atari 7800 YM2149 Sigrok Analyzer (AI-Generated)
Consolidated tool for verifying YM2149 bus timing and reliability.
This tool was generated by an AI assistant to analyze high-speed hardware captures.
(Note: The author admits they don't even know how to code in Python and would have surrendered to the data noise without this AI-powered "X-Ray").

Sigrok Pin Mapping (fx2lafw):
D0: A15
D1: A14
D2: A0
D3: HALT
D4: RW
D5: PHI2
D6: BC1
D7: BDIR
"""

def analyze_capture(filename, sample_rate=24000000):
    try:
        with open(filename, 'rb') as f:
            data = f.read()
    except FileNotFoundError:
        print(f"Error: {filename} not found.")
        return

    sample_period_ns = 1e9 / sample_rate
    last_phi2 = 0
    pulses = []
    
    print(f"Analyzing {filename} ({len(data)} samples)...")
    
    for i in range(len(data)):
        s = data[i]
        phi2 = (s >> 5) & 1
        
        # Detect PHI2 Rising Edge
        if phi2 == 1 and last_phi2 == 0:
            bdir = (s >> 7) & 1
            bc1 = (s >> 6) & 1
            
            # If the sound chip is being hit
            if bdir or bc1:
                # Measure pulse width
                width = 0
                for j in range(i, min(i+100, len(data))):
                    if (data[j] >> 5) & 1 == 1:
                        # Check if BDIR/BC1 falls before PHI2 ends
                        if not ((data[j] >> 7) & 1 or (data[j] >> 6) & 1):
                            break
                        width += 1
                    else:
                        break
                
                pulses.append({
                    'sample': i,
                    'bdir': bdir,
                    'bc1': bc1,
                    'a0': (s >> 2) & 1,
                    'halt': (s >> 3) & 1,
                    'width_ns': width * sample_period_ns
                })
        last_phi2 = phi2

    if not pulses:
        print("No YM2149 activity detected.")
        return

    # Group pulses into bursts (separated by > 1000 samples for notes)
    bursts = []
    current_burst = [pulses[0]]
    for p in pulses[1:]:
        if p['sample'] - current_burst[-1]['sample'] < 1000:
            current_burst.append(p)
        else:
            bursts.append(current_burst)
            current_burst = [p]
    bursts.append(current_burst)

    print(f"\nSummary:")
    print(f"  Total pulses detected: {len(pulses)}")
    print(f"  Total write bursts:    {len(bursts)}")
    
    # Analyze pulse widths
    widths = [p['width_ns'] for p in pulses]
    avg_width = sum(widths) / len(widths)
    min_width = min(widths)
    print(f"  Min Pulse Width: {min_width:.1f}ns")
    print(f"  Avg Pulse Width: {avg_width:.1f}ns")
    
    if min_width < 300:
        print("  WARNING: Pulses detected below YM2149 300ns requirement!")

    # Burst Analysis (Target: Quad-Tap = 8 pulses per burst if ADDR+DATA combined)
    print("\nBurst Detail (First 10):")
    for i, b in enumerate(bursts[:10]):
        type_str = "ADDR/DATA MIX" if any(p['bc1'] for p in b) and not all(p['bc1'] for p in b) else "DATA"
        if all(p['bc1'] for p in b): type_str = "ADDR"
        print(f"  Burst {i+1:2}: {len(b):2} pulses | {type_str:10} | Sample: {b[0]['sample']}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Analyze YM2149 Sigrok captures.')
    parser.get_default('filename')
    parser.add_argument('filename', help='Sigrok binary capture file')
    parser.add_argument('--rate', type=int, default=24000000, help='Samplerate (default 24M)')
    
    args = parser.parse_args()
    analyze_capture(args.filename, args.rate)
